name: Test Dockerfile and requirements

on: [push, pull_request]

jobs:
  run_pip_install:
    name: Merge and install requirements.txt
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        python -m pip install poetry

    - name: Get client requirements.txt
      run: |
        wget https://raw.githubusercontent.com/aiarena/aiarena-client/master/requirements.txt -O client-requirements.txt

    - name: Install client requirements.txt
      run: |
        poetry add $(cat client-requirements.txt)

    - name: Export requirements.txt
      run: |
        poetry export -f requirements.txt --output requirements.txt --without-hashes

    - name: Install requirements.txt via pip
      run: |
        pip install -r requirements.txt

  run_docker_build:
    name: Run docker build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1

    - name: Build docker image
      run: |
        docker build -t aiarena -f Dockerfile .
